### PR TITLE
Adding is_disabled option

### PR DESCRIPTION
**Pull request by cheyner**

### CODE REVIEW

**Comment by cheyner** [comment]
The underlying Analytics package will simply return a NullResponse when prompted to send events to GA if the is_disabled boolean is passed into its constructor.  Ideally I would have included a test here, but there didn't appear to be a simple way to check that -- and it seemed like a fairly benign adjustment to me.

**Comment by kyranb** [comment]
@pascalbaljet Can we help merge this in?

**Comment by sebastiaanluca** [comment]
👋  Was looking for a way to disable the package during tests. Currently it sends a ton of requests to Google 😬

**Comment by pascalbaljet** [comment]
I've changed it to `is_enabled`. Available in v1.5.1 :)

**Pull request merged**
